package com.romiusse.edit_todo.compose

import androidx.compose.ui.graphics.Color


     val support_separator: Color = Color(0x33000000)
     val support_overlay: Color = Color(0x0F000000)
     val label_primary: Color = Color(0xFF000000)
     val label_secondary: Color = Color(0x99000000)
     val label_tertiary: Color = Color(0x4D000000)
     val label_disable: Color = Color(0x26000000)
     val color_red: Color = Color(0xFFFF3B30)
     val color_green: Color = Color(0xFF34C759)
     val color_blue: Color = Color(0xFF007AFF)
     val color_gray: Color = Color(0xFF8E8E93)
     val color_gray_light: Color = Color(0xFFD1D1D6)
     val color_white: Color = Color(0xFFFFFFFF)
     val back_primary: Color = Color(0xFFF7F6F2)
     val back_secondary: Color = Color(0xFFFFFFFF)
     val back_elevated: Color = Color(0xFFFFFFFF)

     val dark_support_separator: Color = Color(0x33FFFFFF)
     val dark_support_overlay: Color = Color(0x52000000)
     val dark_label_primary: Color = Color(0xFFFFFFFF)
     val dark_label_secondary: Color = Color(0x99FFFFFF)
     val dark_label_tertiary: Color = Color(0x66FFFFFF)
     val dark_label_disable: Color = Color(0x26FFFFFF)
     val dark_color_red: Color = Color(0xFFFF453A)
     val dark_color_green: Color = Color(0xFF32D74B)
     val dark_color_blue: Color = Color(0xFF0A84FF)
     val dark_color_gray: Color = Color(0xFF8E8E93)
     val dark_color_gray_light: Color = Color(0xFF48484A)
     val dark_color_white: Color = Color(0xFFFFFFFF)
     val dark_back_primary: Color = Color(0xFF161618)
     val dark_back_secondary: Color = Color(0xFF252528)
     val dark_back_elevated: Color = Color(0xFF3C3C3F)



val md_theme_light_primary = Color(0xFF000000)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFF7F6F2)
val md_theme_light_onPrimaryContainer = Color(0xFF291800)
val md_theme_light_secondary = Color(0xFF6F5B40)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFBDEBC)
val md_theme_light_onSecondaryContainer = Color(0xFF271904)
val md_theme_light_tertiary = Color(0xFF51643F)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD4EABB)
val md_theme_light_onTertiaryContainer = Color(0xFF102004)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1F1B16)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1F1B16)
val md_theme_light_surfaceVariant = Color(0xFFF0E0CF)
val md_theme_light_onSurfaceVariant = Color(0xFF4F4539)
val md_theme_light_outline = Color(0xFF817567)
val md_theme_light_inverseOnSurface = Color(0xFFF9EFE7)
val md_theme_light_inverseSurface = Color(0xFF34302A)
val md_theme_light_inversePrimary = Color(0xFFFFB951)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF825500)
val md_theme_light_outlineVariant = Color(0xFFD3C4B4)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB951)
val md_theme_dark_onPrimary = Color(0xFF452B00)
val md_theme_dark_primaryContainer = Color(0xFF633F00)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDDB3)
val md_theme_dark_secondary = Color(0xFFDDC2A1)
val md_theme_dark_onSecondary = Color(0xFF3E2D16)
val md_theme_dark_secondaryContainer = Color(0xFF56442A)
val md_theme_dark_onSecondaryContainer = Color(0xFFFBDEBC)
val md_theme_dark_tertiary = Color(0xFFB8CEA1)
val md_theme_dark_onTertiary = Color(0xFF243515)
val md_theme_dark_tertiaryContainer = Color(0xFF3A4C2A)
val md_theme_dark_onTertiaryContainer = Color(0xFFD4EABB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1F1B16)
val md_theme_dark_onBackground = Color(0xFFEAE1D9)
val md_theme_dark_surface = Color(0xFF1F1B16)
val md_theme_dark_onSurface = Color(0xFFEAE1D9)
val md_theme_dark_surfaceVariant = Color(0xFF4F4539)
val md_theme_dark_onSurfaceVariant = Color(0xFFD3C4B4)
val md_theme_dark_outline = Color(0xFF9C8F80)
val md_theme_dark_inverseOnSurface = Color(0xFF1F1B16)
val md_theme_dark_inverseSurface = Color(0xFFEAE1D9)
val md_theme_dark_inversePrimary = Color(0xFF825500)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB951)
val md_theme_dark_outlineVariant = Color(0xFF4F4539)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF825500)